name: Post Release PR Merge

on:
  pull_request:
    types: [ closed ]

jobs:
  release_merge:
    if: github.head_ref == 'release/next' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
      - name: Install cz
        run: pip install --user -U Commitizen
      - name: Record release version
        run: |
          echo "RELEASE_VERSION=$(cz version --project)" >> $GITHUB_ENV
      - name: Tag release
        run: |
          git tag $RELEASE_VERSION
          git push origin $RELEASE_VERSION
      - name: Record changelog for current release
        run: cz changelog $RELEASE_VERSION --file-name="release.md"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          title: Release ${{ env.RELEASE_VERSION }}
          name: "Release ${{ env.RELEASE_VERSION }}"
          tag: ${{ env.RELEASE_VERSION }}
          bodyFile: "release.md"
